remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

title: Creating a more holistic Credit Score for Consumers
description: Lakshmikethan Bethamcharla, Darren Jiang, Sheng Zhou, Victor Thai

github:
  is_project_page: True
  repository_url: https://github.com/JiaDarren/DSC_180A
