remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

title: Multi-label Disease Prediction Based on Gut Microbiome
description: UCSD HDSI Capstone Project (Renaldy Herlim, Amando Jimenez, Emerson Chao)

github:
  is_project_page: false
  repository_url: https://github.com/your-github-username/your-repository
